config/routes.rb
BestNycSchools::Application.routes.draw do
  devise_for :users

  root :to => "home#index"
  resources :apartments

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  attr_accessible :address, :rent, :school_zone_id, :latitude, :longitude
  belongs_to :school_zone

  geocoded_by :address
  after_validation :geocode # auto-fetch coordinates
  # , :if => :address_changed?
end

app/models/district.rb
class District < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :school_zones
  has_many :apartments, :through => :school_zones
end

app/models/school_zone.rb
class SchoolZone < ActiveRecord::Base
  attr_accessible :dbn_num, :district_id, :shape_length, :shape_area, :district_num, :school_name, :school_level, :overall_score, :overall_grade, :progress_score, :progress_grade, :performance_score, :performance_grade, :environment_score, :environment_grade
  belongs_to :district
  validates :dbn_num, uniqueness: true
  validates :dbn_num, length: { is: 6}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  def index
    @school_data = SchoolZone.all
    @apartments = Apartment.all
    #  if params
    #   @latitude = params[:latitude]
    #   @longitude = params[:longitude]
    # end
  end
  def create
    latlng_array = Geocoder.coordinates(params[:search])
    binding.pry
    redirect_to '/apartments'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to "/apartments"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apartments/index.html.erb
<script type="text/javascript">window.onload=function(){handler = Gmaps.build('Google');
handler.buildMap({ provider: { center: new google.maps.LatLng(40.775,-73.985), zoom: 12 }, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 0,
      "lng": 0,
      "picture": {
        "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
        "width":  36,
        "height": 36
      },
      "infowindow": "hello!"
    }
  ]);
  // handler.bounds.extendWith(markers);
  // handler.fitMapToBounds();
});
};
</script>

<%= form_tag apartments_path, :method => :post do %>
  <p>
    <%= text_field_tag :search,  params[:search], placeholder: 'Apartment address...' %>
    <%= submit_tag "Find Zoned School", :name => nil %>
<% end %>

<% @apartments.each do |apartment| %>
	<%= @latlng_array[0] %>
	<%= @latlng_array[1] %>
<% end %>

<div style='width: 1000px;'>
  <div id="map" style='width: 1000px; height: 800px;'></div>
</div>

<table>
	<thead>
		<th>DBN</th>
		<th>District</th>
		<th>School</th>
		<th>Level</th>
		<th>Overall Score</th>
		<th>Overall Grade</th>
		<th>Progress Score</th>
		<th>Progress Grade</th>
		<th>Performance Score</th>
		<th>Performance Grade</th>
		<th>Environement Score</th>
		<th>Environment Grade</th>
		<th>Shape Length</th>
		<th>Shape Area</th>
	</thead>
	<tbody>
		<% @school_data.each do |t| %>
			<tr>
				<td><%= t.dbn_num %></td>
				<td><%= t.district_num %></td>
				<td><%= t.school_name %></td>
				<td><%= t.school_level %></td>
				<td><%= t.overall_score %></td>
				<td><%= t.overall_grade %></td>
				<td><%= t.progress_score %></td>
				<td><%= t.progress_grade %></td>
				<td><%= t.performance_score %></td>
				<td><%= t.performance_grade %></td>
				<td><%= t.environment_score %></td>
				<td><%= t.environment_grade %></td>
				<td><%= t.shape_length %></td>
				<td><%= t.shape_area %></td>
			</tr>
		<% end %>
	<tbody/>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BestNycSchools</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>

</body>
</html>